#!/usr/bin/env bash

INSTALL_DIR=$(eval readlink -f "${INSTALL_DIR}")

source ${utils_scripts}/utils.sh
log begin
ensure_home_var_is_set

install_dnsmasq () {
    if [[ ! -e /etc/dnsmasq.conf ]] || [[ "$(grep -c "This file was generated by Starlings" /etc/dnsmasq.conf)" == "0" ]]
    then
        bash ${utils_scripts}/install-components.sh dnsmasq
        sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.ori
        sudo cp ${scripts}/config/dnsmasq.conf /etc/dnsmasq.conf
        case "$(get_os_distribution)" in
            "ubuntu" | "debian" | "mint")
                echo -e "\nIGNORE_RESOLVCONF=yes\n" | sudo tee -a /etc/default/dnsmasq > /dev/null 2>&1
                # Add 'node.dc1.starlings' as domain name
                # TODO WARNING: Not already works on Ubuntu !!!
                if [[ "`egrep -q '^[[:blank:]]*dns-nameservers' ; echo $?`" == "1" ]]
                then
                    sudo bash << EOF
                    sed -i "/iface eth0/a\dns-nameservers 127.0.0.1" /etc/network/interfaces.d/eth0.cfg
EOF
                else
                    sudo bash << EOF
                    sed -i "s/dns-nameservers/dns-nameservers 127.0.0.1/" /etc/network/interfaces.d/eth0.cfg
EOF
                fi
                if [[ "`egrep -q '^[[:blank:]]*dns-search' ; echo $?`" == "1" ]]
                then
                    sudo bash << EOF
                    sed -i "/dns-nameservers/a\dns-search node.dc1.starlings" /etc/network/interfaces.d/eth0.cfg
EOF
                else
                    sudo bash << EOF
                    sed -i "s/dns-search/dns-search node.dc1.starlings/" /etc/network/interfaces.d/eth0.cfg
EOF
                fi
                sudo ifdown eth0; sudo ifup eth0
                ;;
             "centos" | "redhat" | "fedora")
                sudo systemctl enable dnsmasq
                sudo cp /etc/resolv.conf /etc/resolv.dnsmasq.conf
                echo -e "\nresolv-file=/etc/resolv.dnsmasq.conf\n" | sudo tee -a /etc/dnsmasq.conf > /dev/null 2>&1
                sudo sed -i -e "/PEERDNS/ s/^/#/g" /etc/sysconfig/network-scripts/ifcfg-eth*
                echo -e "\nPEERDNS=no\n" | sudo tee -a /etc/sysconfig/network-scripts/ifcfg-eth* > /dev/null 2>&1
                echo -e "# Generated with starlings to enable dnsmasq\n\nnameserver 127.0.0.1\nsearch node.dc1.starlings\n" | sudo tee /etc/resolv.conf > /dev/null 2>&1
                ;;
        esac
        sudo service dnsmasq restart
    fi
}


if [[ "${INSTALL_DNSMASQ}" == "true" ]]; then
    log "info" "Installing DnsMasq"
    install_dnsmasq
fi

mkdir -p "${INSTALL_DIR}/work" "${INSTALL_DIR}/config"
cp ${scripts}/consul "${INSTALL_DIR}/"
chmod +x ${INSTALL_DIR}/consul

sed -e "s@#INSTALL_DIR#@${INSTALL_DIR}@g" -e "s/#IP#/${IP_ADDRESS}/g"  ${scripts}/config/1_main_conf.json > "${INSTALL_DIR}/config/1_main_conf.json"

mkdir -p ${HOME}/.starlings
echo "CONSUL_HOME=${INSTALL_DIR}" >${HOME}/.starlings/starlings_consul_env.sh

# Setup systemd service
# Setup GOMAXPROCS to the number of cpu
export GOMAXPROCS=$(cat /proc/cpuinfo | grep processor | wc -l)
sudo cp ${scripts}/systemd/consul.service /etc/systemd/system/consul.service
sudo sed -i -e "s/{{USER}}/${USER}/g" -e "s@{{CONSUL_HOME}}@${INSTALL_DIR}@g" -e "s/{{GOMAXPROCS}}/${GOMAXPROCS}/g" /etc/systemd/system/consul.service
sudo systemctl daemon-reload

log end "Consul installed in ${INSTALL_DIR}"
