tosca_definitions_version: alien_dsl_2_0_0

metadata:
  template_name: org.alien4cloud.alien4cloud.config.location_resources.autoconfig
  template_version: 2.2.0-SNAPSHOT
  template_author: alien4cloud

imports:
  - alien-base-types:2.2.0-SM9
  - org.alien4cloud.alien4cloud.config.location:2.2.0-SNAPSHOT
  - org.alien4cloud.cloudify.hostpool.pub:2.2.0-SNAPSHOT
  - tosca-normative-types:1.0.0-ALIEN20

node_types:

  org.alien4cloud.alien4cloud.config.location_resources.autoconfig.nodes.ResourcesConfigurator:
    description: |
      Configure a location for A4C, resources are fed using a resource yaml file
    derived_from: org.alien4cloud.alien4cloud.config.location.nodes.SimpleLocationConfigurator
    artifacts:
      - resources_file_artifact:
          type: tosca.artifacts.File
    interfaces:
      Standard:
        start:
          # create the location on demand resources
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: create_location_resources.yml
            orchestratorId: { get_attribute: [HOST, orchestratorId] }
            locationId: { get_attribute: [SELF, locationId] }
            alien_url: { get_attribute: [HOST, alien_url] }
            alien_user: { get_attribute: [HOST, alien_user] }
            alien_password: { get_attribute: [HOST, alien_password] }
          implementation: playbook/playbook.ansible
