tosca_definitions_version: alien_dsl_2_0_0

metadata:
  template_name: org.alien4cloud.alien4cloud.config.location_resources.cfy_byon
  template_version: 2.2.0-SNAPSHOT
  template_author: alien4cloud

imports:
  - alien-base-types:2.2.0-SM9
  - org.alien4cloud.alien4cloud.config.location:2.2.0-SNAPSHOT
  - org.alien4cloud.cloudify.hostpool.pub:2.2.0-SNAPSHOT
  - org.alien4cloud.cloudify.manager.pub:2.2.0-SNAPSHOT
  - tosca-normative-types:1.0.0-ALIEN20

node_types:

  org.alien4cloud.alien4cloud.config.location_resources.cfy_byon.nodes.ByonLocationResourcesConfigurator:
    description: |
      Configure a BYON location for A4C with a single on-demand resource
    derived_from: org.alien4cloud.alien4cloud.config.location.nodes.SimpleLocationConfigurator
    properties:
      type:
        type: string
        required: true
        default: byon
        constraints:
          - valid_values: [ "byon" ]
      resourceType:
        type: string
        required: true
        default: alien.cloudify.byon.nodes.LinuxCompute
      resourceName:
        type: string
        required: true
        default: MyResource
      resourceArchiveName:
        type: string
        required: true
        default: cloudify-byon-types
      resourceArchiveVersion:
        type: string
        required: true
        default: 2.2.0-SNAPSHOT
      resourceAgentInstallMethod:
        type: string
        required: true
        default: none
    requirements:
      - hostpool:
          capability: org.alien4cloud.cloudify.hostpool.pub.capabilities.HostPoolServiceApi
          relationship: org.alien4cloud.alien4cloud.config.location_resources.cfy_byon.LocationConnectsToHostpool
          occurrences: [1, 1]
    interfaces:
      Standard:
        start:
          # create the location on demand resources
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: create_byon_location_resource.yml
            orchestratorId: { get_attribute: [HOST, orchestratorId] }
            locationId: { get_attribute: [SELF, locationId] }
            alien_url: { get_attribute: [HOST, alien_url] }
            alien_user: { get_attribute: [HOST, alien_user] }
            alien_password: { get_attribute: [HOST, alien_password] }
            resourceType: { get_property: [SELF, resourceType] }
            resourceName: { get_property: [SELF, resourceName] }
            resourceArchiveName: { get_property: [SELF, resourceArchiveName] }
            resourceArchiveVersion: { get_property: [SELF, resourceArchiveVersion] }
            resourceAgentInstallMethod: { get_property: [SELF, resourceAgentInstallMethod] }
          implementation: playbook/playbook.ansible

relationship_types:

  org.alien4cloud.alien4cloud.config.location_resources.cfy_byon.LocationConnectsToHostpool:
    derived_from: tosca.relationships.ConnectsTo
    valid_target_types: [ org.alien4cloud.cloudify.hostpool.pub.capabilities.HostPoolServiceApi ]
    interfaces:
      Configure:
        pre_configure_source:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: connect_hostpool.yml
            hostpool_url: { concat: [get_property: [TARGET, cloudify_hostpool, protocol], "://", get_attribute: [TARGET, cloudify_hostpool, ip_address], ":", get_property: [TARGET, cloudify_hostpool, port]] }
          implementation: playbook/playbook.ansible
